### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by azarus** [RoobinGood/ytdl-playlist#2]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

**Comment by azarus** [comment]
Your stuff simply doesnt work. :x

**Comment by RoobinGood** [comment]
@azarus the problem was in outdated `ytdl-core` dependency. Maybe something was changed in youtube API and old version doesn't work.

I bump `ytdl-core` version and now it's working.

Thanks for issue )
