### ISSUE TITLE
submit to npm?

### ISSUE THREAD

**Issue by chez14** [RoobinGood/ytdl-playlist#3]
It seems like better to use it on command line protably...

Why don't you submit one to NPM? 😄

**Comment by chez14** [comment]
I'll publish it to NPM, is it ok?

**Comment by RoobinGood** [comment]
Sorry for long response time.
I think that publish it to NPM is not good idea. This tool was created for fun and learning and not ready for use in common case.
But anyway I will fix some things in tool and publish it soon.
Thank you.

**Comment by chez14** [comment]
ohh ok, got it mate, hahaha

I'll close this issue now, thanks!
